apiVersion: batch/v1
kind: Job
metadata:
  name: model-prep
spec:
  template:
    spec:
      containers:
      - name: model-prep
        image: model-prep:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "8Gi"
            nvidia.com/gpu: "1"
          requests:
            memory: "4Gi"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "1Gi"
      restartPolicy: Never 